export {default as Jobs} from './Jobs'
export {default as Partners} from './Partners'
export {default as Consultation} from './Consultation'
export {default as Services} from './Services'
// export {default as Jobs} from './Jobs'